version: 2
updates:
  # Enable npm dependency updates
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "ajstack22"
    labels:
      - "dependencies"
      - "security"
    # Group patch updates together
    groups:
      patch-updates:
        update-types:
          - "patch"
    # Ignore major version bumps for now (too risky)
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "deps"
      include: "scope"