blank_issues_enabled: false
contact_links:
  - name: 💬 Community Discussions
    url: https://github.com/yourusername/manylla/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📚 Documentation
    url: https://github.com/yourusername/manylla/tree/main/docs
    about: Check our documentation for answers
  - name: 🔒 Security Issues
    url: https://github.com/yourusername/manylla/security/policy
    about: Please report security vulnerabilities here