import { CategoryConfig } from '../types/ChildProfile';

// Unified categories combining Quick Info and regular categories
export const unifiedCategories: CategoryConfig[] = [
  // Former Quick Info - now priority categories at top
  {
    id: 'emergency',
    name: 'emergency',
    displayName: 'Emergency',
    color: '#E74C3C',
    order: 1,
    isVisible: true,
    isCustom: false,
    isQuickInfo: true,
  },
  {
    id: 'medical',
    name: 'medical', 
    displayName: 'Medical',
    color: '#E67E22',
    order: 2,
    isVisible: true,
    isCustom: false,
    isQuickInfo: true,
  },
  {
    id: 'communication',
    name: 'communication',
    displayName: 'Communication',
    color: '#3498DB',
    order: 3,
    isVisible: true,
    isCustom: false,
    isQuickInfo: true,
  },
  {
    id: 'sensory',
    name: 'sensory',
    displayName: 'Sensory',
    color: '#9B59B6',
    order: 4,
    isVisible: true,
    isCustom: false,
    isQuickInfo: true,
  },
  {
    id: 'dietary',
    name: 'dietary',
    displayName: 'Dietary',
    color: '#27AE60',
    order: 5,
    isVisible: true,
    isCustom: false,
    isQuickInfo: true,
  },
  {
    id: 'medications',
    name: 'medications',
    displayName: 'Medications',
    color: '#E74C3C',
    order: 6,
    isVisible: true,
    isCustom: false,
    isQuickInfo: true,
  },
  {
    id: 'allergies',
    name: 'allergies',
    displayName: 'Allergies',
    color: '#C0392B',
    order: 7,
    isVisible: true,
    isCustom: false,
    isQuickInfo: true,
  },
  {
    id: 'behaviors',
    name: 'behaviors',
    displayName: 'Behaviors',
    color: '#8E44AD',
    order: 8,
    isVisible: false,
    isCustom: false,
    isQuickInfo: true,
  },
  {
    id: 'triggers',
    name: 'triggers',
    displayName: 'Triggers',
    color: '#D35400',
    order: 9,
    isVisible: false,
    isCustom: false,
    isQuickInfo: true,
  },
  {
    id: 'calming',
    name: 'calming',
    displayName: 'Calming Strategies',
    color: '#16A085',
    order: 10,
    isVisible: false,
    isCustom: false,
    isQuickInfo: true,
  },
  {
    id: 'sleep',
    name: 'sleep',
    displayName: 'Sleep',
    color: '#2C3E50',
    order: 11,
    isVisible: false,
    isCustom: false,
    isQuickInfo: true,
  },
  
  // Regular categories
  {
    id: 'medical-history',
    name: 'medical-history',
    displayName: 'Medical History',
    color: '#E74C3C',
    order: 12,
    isVisible: true,
    isCustom: false,
    isQuickInfo: false,
  },
  {
    id: 'development-history',
    name: 'development-history',
    displayName: 'Development History',
    color: '#3498DB',
    order: 13,
    isVisible: true,
    isCustom: false,
    isQuickInfo: false,
  },
  {
    id: 'goals',
    name: 'goals',
    displayName: 'Goals',
    color: '#2ECC71',
    order: 14,
    isVisible: true,
    isCustom: false,
    isQuickInfo: false,
  },
  {
    id: 'successes',
    name: 'successes',
    displayName: 'Successes',
    color: '#F39C12',
    order: 15,
    isVisible: true,
    isCustom: false,
    isQuickInfo: false,
  },
  {
    id: 'strengths',
    name: 'strengths',
    displayName: 'Strengths',
    color: '#16A085',
    order: 16,
    isVisible: true,
    isCustom: false,
    isQuickInfo: false,
  },
  {
    id: 'challenges',
    name: 'challenges',
    displayName: 'Challenges',
    color: '#E67E22',
    order: 17,
    isVisible: true,
    isCustom: false,
    isQuickInfo: false,
  },
  {
    id: 'caretaker-history',
    name: 'caretaker-history',
    displayName: 'Caretaker History',
    color: '#9B59B6',
    order: 18,
    isVisible: true,
    isCustom: false,
    isQuickInfo: false,
  },
  {
    id: 'phrases',
    name: 'phrases',
    displayName: 'Phrases',
    color: '#8E44AD',
    order: 19,
    isVisible: true,
    isCustom: false,
    isQuickInfo: false,
  },
  {
    id: 'tips-tricks',
    name: 'tips-tricks',
    displayName: 'Tips & Tricks',
    color: '#27AE60',
    order: 20,
    isVisible: true,
    isCustom: false,
    isQuickInfo: false,
  },
  {
    id: 'daily-routine',
    name: 'daily-routine',
    displayName: 'Daily Routine',
    color: '#34495E',
    order: 21,
    isVisible: true,
    isCustom: false,
    isQuickInfo: false,
  },
  {
    id: 'education',
    name: 'education',
    displayName: 'Education',
    color: '#2980B9',
    order: 22,
    isVisible: true,
    isCustom: false,
    isQuickInfo: false,
  },
  {
    id: 'therapy',
    name: 'therapy',
    displayName: 'Therapy',
    color: '#1ABC9C',
    order: 23,
    isVisible: true,
    isCustom: false,
    isQuickInfo: false,
  },
];

export function getCategoryByName(categories: CategoryConfig[], name: string): CategoryConfig | undefined {
  return categories.find(cat => cat.name === name);
}

export function getVisibleCategories(categories: CategoryConfig[]): CategoryConfig[] {
  return categories
    .filter(cat => cat.isVisible)
    .sort((a, b) => a.order - b.order);
}

// Migrate from old quick info format to unified categories
export function migrateQuickInfoToCategories(quickInfoValue: string, categoryName: string): any {
  if (!quickInfoValue) return null;
  
  return {
    id: `migrated-${categoryName}-${Date.now()}`,
    title: categoryName.charAt(0).toUpperCase() + categoryName.slice(1),
    description: quickInfoValue,
    category: categoryName,
    date: new Date(),
    visibility: 'private' as const,
  };
}