package com.manylla

import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReactContextBaseJavaModule

class BuildConfigModule(reactContext: ReactApplicationContext) :
    ReactContextBaseJavaModule(reactContext) {

    override fun getName(): String {
        return "BuildConfigModule"
    }

    override fun getConstants(): Map<String, Any> {
        val constants: MutableMap<String, Any> = HashMap()

        // Get BUILD_TYPE_ENV and API_ENDPOINT from BuildConfig (generated by product flavors)
        constants["BUILD_TYPE"] = BuildConfig.BUILD_TYPE_ENV
        constants["API_ENDPOINT"] = BuildConfig.API_ENDPOINT
        constants["BUNDLE_ID"] = BuildConfig.APPLICATION_ID

        android.util.Log.d(
            "BuildConfigModule",
            "Exporting constants - BUILD_TYPE=${BuildConfig.BUILD_TYPE_ENV}, " +
            "API_ENDPOINT=${BuildConfig.API_ENDPOINT}, " +
            "BUNDLE_ID=${BuildConfig.APPLICATION_ID}"
        )

        return constants
    }
}
