#!/bin/bash
# Automatic Rollback Script
# Generated by deployment-preflight.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
BACKUP_DIR="/tmp/manylla-backup-20250923-094511"

echo "🔄 Rolling back Manylla deployment..."

cd "$PROJECT_ROOT"

# Restore package.json version if backup exists
if [ -f "$BACKUP_DIR/previous-version.txt" ]; then
    PREVIOUS_VERSION=$(cat "$BACKUP_DIR/previous-version.txt")
    echo "Restoring version to: $PREVIOUS_VERSION"

    if [[ "$OSTYPE" == "darwin"* ]]; then
        sed -i '' "s/\"version\": \".*\"/\"version\": \"$PREVIOUS_VERSION\"/" package.json
    else
        sed -i "s/\"version\": \".*\"/\"version\": \"$PREVIOUS_VERSION\"/" package.json
    fi
fi

# Restore web/build if backup exists
if [ -d "$BACKUP_DIR/web-build-backup" ]; then
    echo "Restoring web/build directory..."
    rm -rf web/build
    cp -r "$BACKUP_DIR/web-build-backup" web/build
fi

# Find and restore remote backup
echo "Restoring remote files..."
LATEST_BACKUP=$(ssh stackmap-cpanel "ls -t ~/manylla-qual-backup-*.tar.gz 2>/dev/null | head -1" || echo "")

if [ -n "$LATEST_BACKUP" ]; then
    ssh stackmap-cpanel "
        cd ~/public_html/manylla/qual &&
        rm -rf * .htaccess 2>/dev/null || true &&
        tar -xzf $LATEST_BACKUP &&
        echo 'Remote files restored'
    "
    echo "✅ Rollback completed successfully"
else
    echo "❌ No remote backup found for restoration"
    exit 1
fi

echo "🔍 Running health check..."
curl -s -o /dev/null -w "Health check: HTTP %{http_code}\n" https://manylla.com/qual/

echo "✅ Rollback process completed"
