#!/bin/bash
# Automatic Rollback Script
# Generated by deployment-preflight.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
BACKUP_DIR="/tmp/manylla-backup-20250915-173640"

echo "🔄 Rolling back Manylla deployment..."

cd "$PROJECT_ROOT"

# Restore package.json version if backup exists
if [ -f "$BACKUP_DIR/previous-version.txt" ]; then
    PREVIOUS_VERSION=$(cat "$BACKUP_DIR/previous-version.txt")
    echo "Restoring version to: $PREVIOUS_VERSION"

    if [[ "$OSTYPE" == "darwin"* ]]; then
        sed -i '' "s/\"version\": \".*\"/\"version\": \"$PREVIOUS_VERSION\"/" package.json
    else
        sed -i "s/\"version\": \".*\"/\"version\": \"$PREVIOUS_VERSION\"/" package.json
    fi
fi

echo "✅ Rollback completed successfully"
echo "🔍 Running health check..."
echo "Health check: HTTP 200 (simulated)"
echo "✅ Rollback process completed"
