import React from "react";
import { View, Text } from "react-native";
import { usePrintStyles } from "./usePrintStyles";

export const PrintPreviewFooter = ({ colors }) => {
  const styles = usePrintStyles(colors);

  return (
    <View style={styles.documentFooter}>
      <Text style={styles.footerText}>
        This information is confidential. Generated by Manylla on{" "}
        {new Date().toLocaleString()}
      </Text>
    </View>
  );
};
